language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:xw
  fast_finish: true

install:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

script:
  - vendor/bin/phpunit
